### ISSUE TITLE
Sekeletal Embedding Method/s -> Weight Calculation

### ISSUE THREAD

**Issue by Thomas-cr** [PG649-3D-RPG/Creature-Generation#10]

**Comment by Thomas-cr** [comment]
Summary of the methods in our Wiki: https://github.com/PG649-3D-RPG/Creature-Generation/wiki/Automatic-Rigging

**Comment by Leo1998** [comment]
Dual-Quaternion Skinning: erstes Beispiel ist im Branch dq-skinning. Bisher ist Skin nur an den Kopf attached und Transformation scheinbar noch falsch.
