### ISSUE TITLE
Hacked DQ shader is not exported correctly

### ISSUE THREAD

**Issue by vuffi-ra** [PG649-3D-RPG/Creature-Generation#121]
When the package is imported into a different Unity project, Shader.Find returns null when trying to find the hacked DQ shader.

Steps to reproduce:
1. In CreatureGeneratorSettings::onEnable replace the material initalization with `MeshSettings.Material = new Material(Shader.Find("MadCake/Material/Standard hacked for DQ skinning"));`
2. Import the package into a different Unity project
3. Console warns about null shader

I assume there is something special we need to do to export shaders.

**Comment by Thomas-cr** [comment]
* Look it up when Bone Heat Method is finished
     * If necessary/not working with the current BHM, start over again
