### ISSUE TITLE
Tracking Issue: Creature Mass

### ISSUE THREAD

**Issue by nconotor** [PG649-3D-RPG/Creature-Generation#124]
It seems the creature is floating a little with standard gravity. We should try to train it with gravity 1 and scale the mass of the creature. A mass scale would be good. Doubling to tripling the mass seems to produce better results.

This issue should also track improvements with the calculation of the weights. As far as we know, weights are calculated per size of the bones. This is kind of problematic. If we look at real creatures, bone size, body tissue etc. are factors for the weight. Also, parts are flatter/bigger than in our creature, which consist only of spheres.

We need a better, more realistic approach for it.

- [x] #130
- [x] #131
- [ ] https://github.com/PG649-3D-RPG/Creature-Generation/issues/141

**Comment by Thomas-cr** [comment]
2x - 3x seems to be enough (currently 3x)

**Comment by nconotor** [comment]
We use fixed masses till we know more. Therefore, this is closed till further notice.
