### ISSUE TITLE
Investigate if packages can be downgraded

### ISSUE THREAD

**Issue by nconotor** [PG649-3D-RPG/Creature-Generation#125]
Normal unity packages can be downgraded. Can we do it with git? If you change the package the creature changes as well. This might lead to problems. 

We could change the git url to a specific commit... But unity might bug out, if we do that. This issue is not that important tho. Don't waste too much time on it.

Also, please remember to push version number up if you change something. :)

**Comment by vuffi-ra** [comment]
Answer seems to be [no](https://forum.unity.com/threads/how-can-i-use-upms-versioning-with-git-urls.974814/).
