### ISSUE TITLE
Spawn biped and quadruped creatures with the same rotation

### ISSUE THREAD

**Issue by nconotor** [PG649-3D-RPG/Creature-Generation#138]
Currently, we need different rotations for them. They should both spawn with the legs pointing to the ground.

**Comment by Thomas-cr** [comment]
Carsten ansprechen

**Comment by Thomas-cr** [comment]
* Vermutung von Carsten: Problematik von der Animator-Seite
* Hinzugefügter Offset (Root-Bone) von Jona
