### ISSUE TITLE
Insert proportional limits to generation

### ISSUE THREAD

**Issue by nconotor** [PG649-3D-RPG/Creature-Generation#141]
Eine Idee vielleicht, um reproduzierbar "besser" aussehende Kreaturen zu bekommen. Ich habe aber keine Ahnung, ob das, was kompliziertes oder Einfaches ist. Könnte der Zufallsgenerator jeweils die Proportionen zu anderen wichtigen Elementen checken?

Ein Beispiel hier: https://i.imgur.com/2qo6L1x.png
Die Hände sind extrem groß in Relation zu den Armen und das mittlere Torsoelement sehr lang.
Wenn der Generator jetzt Werte hätte "Die Hände nicht mehr als 50 % dicker als die Arme" oder der mittlere Knochen nicht länger als 30 % der umliegenden Wirbel, sollte die ganzen Proportionen doch besser verteilt werden? (Die Werte sind ausgedacht, die müsste man dann rausfinden)

Das würde vielleicht auch die Gewichtsverteilung ohne irgendwelche manuellen Eingriffe verbessern.

**Comment by Thomas-cr** [comment]
Markus mit Animatorn Feedbackrunde einstellen

**Comment by nconotor** [comment]
Irrelevant geworden durch die ganzen Änderungen
