### ISSUE TITLE
Animation Fixes

### ISSUE THREAD

**Issue by nconotor** [PG649-3D-RPG/Creature-Generation#171]
This issue will track our most important task for the creature

- [ ] Avoid spawning joints in another under any circumstances
- [x] Avoid small Joint angles of Angular Y Limit and Angular Z Limit. Depending on your setup, the minimum angles should be around 5 to 15 degrees in order to be stable. Instead of using a small angle, try setting the angle to zero. This locks the axis and provide a stable simulation.
- [x] Uncheck the Joint’s Enable Preprocessing property. 
- [x] "Avoid large differences in the masses between Rigidbody components connected by Joints. It’s okay to have one Rigidbody with twice as much mass as another, but when one mass is ten times larger than the other, the simulation can become jittery." -> We will use fixed masses for the foreseeable future

**Comment by Thomas-cr** [comment]
* Torso angles: bigger or even locked (-> beware the stiffness!) ?

**Comment by nconotor** [comment]
@Thomas-cr good question. I would say (If it is not too much work) add an option and we will see whether it is useful or not.

**Comment by Thomas-cr** [comment]
* Try setting small angles automatically on locked

**Comment by Thomas-cr** [comment]
Avoid spawning joints in another under any circumstances: fix per parameter
