### ISSUE TITLE
L-System feature completion

### ISSUE THREAD

**Issue by kb1t** [PG649-3D-RPG/Creature-Generation#19]
Implement the missing features

**Comment by Thomas-cr** [comment]
Creature-Animation Anforderungen:
- Torso: 1 Segment (fürs erste)
- Alles was an einem Parent hängt, ist in einer Hierarchie-Ebene
- Benamung: ausgeschrieben & genauso wie der Walker, Reihenfolge der Glieder muss eindeutig sein
- Ankerpunkt entfernen -> Walker muss bei Simulations-start "zusammenbrechen" (-> kein Attach Body Objekt)
- Auf Dauer: Hände & Füße einfügen (anstatt nur Spitze), damit Walker auch stehenbleiben kann -> Somit soll das Ende der Glieder auch erkannt werden können

**Comment by Thomas-cr** [comment]
-Root Knochen des Skelett-Baumes lösen
-Warten auf Feedback der anderen Gruppe (Morgen: 09.06.2022)

**Comment by Thomas-cr** [comment]
- "Cube" in der Figur, nicht vor der Figur
